### ISSUE TITLE
command line

### ISSUE THREAD

**Issue by rmcgibbo** [rmcgibbo/msmbuilder3#1]
try checking out this code on the command line.
there are some examples here: http://rmcgibbo.github.io/msmbuilder3/

cc: @schwancr @kyleabeauchamp

**Comment by kyleabeauchamp** [comment]
Everything looks great to me.  

I am somewhat hesitant to create yet another custom class that wraps PyTables, but I suspect that's the cleanest way to incorporate all the metadata that you want.

**Comment by rmcgibbo** [comment]
I think there could be a better command line syntax for invoking these multistage estimators than

```
msmb kcenters --output assignments.h5 --n_clusters=5 --source=tICA --TICAApp.n_components=2 --TICAApp.source=vector --VectorApp.method=dihedral --VectorApp.index=indices.dat --input trajectories/
```

The design of `--source` is sort of to echo unix pipes, which would suggest a syntax like

```
msmb vector --inout trajectories | msmb tICA --n_components=2 | msmb kcentes --output assignments --n_clusters=5
```

We obviously can't use shell pipes directly, but perhaps there's a command line syntax that could "look" like it.

**Comment by kyleabeauchamp** [comment]
So another thing I was thinking about was ways to make things "print" nicely.  If this interface is going to be our primary interface, I wonder if there are tools for making it prettier.  

PS Robert have you ever looked at SKLL (https://github.com/EducationalTestingService/skll)?  I haven't actually used it, but I wanted to make sure you were aware of its existence.

**Comment by rmcgibbo** [comment]
I'm looking on the keyboard for characters that can be used in place of the pipe character. What about "++"?

The syntax for a chained estimator could very well be

```
msmb vector --input trajectories ++ tICA --n_components=2 ++ kcenters --n_clusters=5 --output assignments.h5
```

?

**Comment by rmcgibbo** [comment]
Are you talking about the `msmb info` command, or printing somewhere else?

**Comment by kyleabeauchamp** [comment]
Or maybe something that looks like an arrow?

**Comment by kyleabeauchamp** [comment]
Yeah, msmb info but also all the command line stuff, but don't worry about that.

**Comment by rmcgibbo** [comment]
It's hard because `<` and `>` already have a meaning within bash/most shells, so if you want them to be a part of the command line, you have to put everything in single quotes.

**Comment by rmcgibbo** [comment]
We could use the carat `^`.

**Comment by kyleabeauchamp** [comment]
So one possible downside to a pipe-like syntax is that it leads to "arcane" looking commands--you're always squeezing lots of things into one line.

One could argue that different calculations should be written as different lines of commands.  Under that model, what we would need is a way to easily pass all the required files with as little typing as possible.

**Comment by kyleabeauchamp** [comment]
Just a thought.

**Comment by rmcgibbo** [comment]
I'm not sure I totally understand. I want everything to be invokable either on its own -- taking input and writing output -- but also as a part of a "pipe". This way if you want to go one step at a time, you have that flexibility. But it is going to be faster computationally in many cases to avoid hitting the disk with intermediate files, especially for things like computing bond lengths and dihedral angles that can be done on the fly for very cheap

**Comment by kyleabeauchamp** [comment]
Got it

**Comment by rmcgibbo** [comment]
So something like this

```
msmb vector --input trajectories/ --output vectors.h5
msmb tICA --input vectors.h5 --output projection.h5
msmb kcenters --input projection.h5 --output assignments.h5
```

Or all in 1 "piped" command should be legit.

**Comment by mpharrigan** [comment]
Do we need a pipe character? What's wrong with

`msmb vector --input=trajectories tICA --n_components=2 kcenters --n_clusters=5 --output assignments.h5`

**Comment by schwancr** [comment]
The trouble is that type of line (if supported) becomes very complicated, very fast. So, our thoughts were to make the library as friendly as possible so that kind of piping would be easy in python-land

**Comment by rmcgibbo** [comment]
My most recent thinking is to try to push the python API by providing tools in python to do this stuff in less than 10 lines of code.

**Comment by mpharrigan** [comment]
Yeah, if there is a 1:1 correspondence between the individual 
command-line commands and python calls, it would be very painless for a 
user to do it in python. Emphasis on that if, though. As a new user to 
msmb2, I was sometimes dismayed that the command line scripts didn't 
correspond directly to one high-level function call
