### ISSUE TITLE
consider renaming `fit_update` `partial_fit`

### ISSUE THREAD

**Issue by rmcgibbo** [rmcgibbo/msmbuilder3#3]
e.g. http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html#sklearn.naive_bayes.MultinomialNB.partial_fit

**Comment by schwancr** [comment]
interesting, I don't have a strong preference either way actually.

**Comment by kyleabeauchamp** [comment]
Ditto
